### ISSUE TITLE
How to build icons

### ISSUE THREAD

**Issue by GarkGarcia** [fiahfy/icns#1]
There's no documentation on how to build the icons...

**Comment by fiahfy** [comment]
Append png buffer by `Icns.appendImage(buffer, osType)`.
Supported osType is defined in https://github.com/fiahfy/icns/blob/master/src/index.js#L55
Get ICNS buffer by `Icns.data` getter.
e.g.
```
;(async () => {
  const icns = new Icns()
  let buf
  buf = fs.readFileSync('./1024x1024.png')
  await icns.appendImage(buf, 'ic10')
  buf = fs.readFileSync('./512x512.png')
  await icns.appendImage(buf, 'ic09')
  buf = icns.data
  fs.writeFileSync('./icon.icns', buf)
})()
```
