### ISSUE TITLE
Extracting icons as PNG buffer

### ISSUE THREAD

**Issue by GarkGarcia** [fiahfy/icns#2]
How can I convert from `IcnsImage`'s image attribute to a PNG encoded buffer?

**Comment by GarkGarcia** [comment]
Also it appears that `Icns.iconImages` does not exists...

**Comment by fiahfy** [comment]
Get `Array<IcnsImage>` by `Icns.images`.
And get png buffer by `IcnsImage.image` from `IcnsImage`.
e.g.
```
;(async () => {
  let buf = fs.readFileSync('./icon.icns')
  const icns = new Icns(buf)
  for (let icnsImage of icns.images) {
    let buf = icnsImage.image
    fs.writeFileSync(`./${icnsImage.osType}.png`, buf)
  }
})()
```

**Comment by GarkGarcia** [comment]
Thanks! One issue I have encountered is that the supported OSTypes are not necessarily encoded in the PNG file format. As stated in [here](https://en.wikipedia.org/wiki/Apple_Icon_Image_format#Icon_types), images with OSType ranging from `ic07` to `ic14` can be encoded either in the PNG format _or_ in the [JPEG 2000](https://en.wikipedia.org/wiki/JPEG_2000) file format, which is not natively supported by [Jimp](https://github.com/oliver-moran/jimp#readme).

We could choose either choose to simply not support those types of images or create a JIMP extension to be able to parse then into Jimp objects. However, the second approach may be a bit out of the scope of this project...

**Comment by fiahfy** [comment]
First, I did not consider JPEG 2000 format.

Jimp is used for validate mime type and image size.
JPEG 2000 format can be detected by [file-type](https://www.npmjs.com/package/file-type) instead of Jimp, but image size is not.

I will fix for JPEG 2000 format, if the above problem is solved.

**Comment by GarkGarcia** [comment]
Yes, the original problem is fixed (it was just a documentation issue).

**Comment by GarkGarcia** [comment]
I'll create a new issue to keep track of the JPEG 200 thing and close this one.
