### ISSUE TITLE
Consider dropping support for types "ic04" and "ic05" in favour of "is32" and "il32" + masks

### ISSUE THREAD

**Issue by ezzatron** [fiahfy/icns#6]
I recently started investigating some issues with my own `.icns` files, which were not working in non-retina situations. I came across your library, which supports the `ic04` and `ic05` types, and I thought that it might produce `.icns` files which would work for non-retina too.

Unfortunately, there seem to be some issues with the ARGB encoding. You can demonstrate this with a pretty strange process, even on a retina machine:

1. Create an `.icns` file with `@fiahfy/icns` that includes `ic04` and `ic05` types
2. Create a new folder in Finder
3. Right-click the new folder and select "Get Info"
4. Drag-drop the `.icns` file onto the folder icon in the top-left
5. Click the same folder icon in the top-left of the "Get Info" dialog
6. Press ⌘+C to copy the icon
7. Open Preview
8. Press ⌘+N to create a new icon from the clipboard
9. Look down through the list of icons and see that some icons look corrupted/glitchy

Side note; I found that that sometimes the macOS Preview app seems to lie about what sizes are in an `.icns` file. It's weird.

I did some more research, and looked into what image types the [Firefox Developer Edition](https://www.mozilla.org/en-US/firefox/developer/) `.icns` file contained. I found that they don't use the `ic04` or `ic05` types. Instead, they use:

- `il32` (RGB) + `l8mk` (alpha mask) = 32x32@1x
- `is32` (RGB) + `s8mk` (alpha mask) = 16x16@1x

Anyway, I figured out how to encode these types, if you are interested. I ended up using `@fiahfy/packbits` directly for the RLE compression. You would have to adapt the implementation, because I used `pngjs` instead of `jimp`, but it's pretty straightforward: https://github.com/iconduit/iconduit/blob/5e8c21b/src/icns.js#L59

The structure of `il32` and `is32` is basically:
1. *(No header)*
2. Red bytes, RLE encoded
3. Green bytes, RLE encoded
4. Blue bytes, RLE encoded
5. *(No alpha channel)*

And both `l8mk` and `s8mk` are just the alpha channel bytes with **no RLE encoding** (pretty weird).

You can see an example file here: https://github.com/iconduit/iconduit/blob/5e8c21b/test/fixture/iconduit/dist/macos.icns?raw=true

**Comment by fiahfy** [comment]
> Unfortunately, there seem to be some issues with the ARGB encoding. You can demonstrate this with a pretty strange process, even on a retina machine:

I tried with the above procedure, but it did not reproduce in my environment.
(macOS Mojave 10.14.6)

> I did some more research, and looked into what image types the Firefox Developer Edition .icns file contained. I found that they don't use the ic04 or ic05 types. Instead, they use:

Thank you for useful information!
I will investigate about `il32+l8mk` and `is32+s8mk`, then consider the support for their types.

**Comment by ezzatron** [comment]
> I tried with the above procedure, but it did not reproduce in my environment.
> (macOS Mojave 10.14.6)

I put together a repo over at https://github.com/ezzatron/fiahfy-icns-repro to demonstrate the weirdness I'm seeing. I will have to wait until next week when I'm back in the office to get access to a non-retina macOS machine to show you the really bad corruption that can happen (if I can even reproduce it).

But even if it's not "corrupted", the `.icns` file still ends up with some broken entries according to Preview:

- `ic04` is broken:

<img width="826" alt="preview-output-icns-ic04" src="https://user-images.githubusercontent.com/100152/68480155-dcfea700-027f-11ea-88e8-5fde52303f5d.png">

- `ic05` looks okay:

<img width="824" alt="preview-output-icns-ic05" src="https://user-images.githubusercontent.com/100152/68480126-c9534080-027f-11ea-8670-2bca7dd68fb3.png">

This is on Catalina, but my work machine is still on Mojave, and I was seeing similar results there. See the repo for a more detailed breakdown.

> Thank you for useful information!
> I will investigate about `il32+l8mk` and `is32+s8mk`, then consider the support for their types.

No problem 👍

**Comment by fiahfy** [comment]
I also checked the behavior using your repository and was able to reproduce the phenomenon that `ic04` is not displayed correctly.

When I tried various things, I found that if I changed the order of appending `ic04` like the code below, it was displayed.

```
  await icns.appendImage(png1024, 'ic10')
  await icns.appendImage(png512, 'ic09')
  await icns.appendImage(png512, 'ic14')
  await icns.appendImage(png256, 'ic08')
  await icns.appendImage(png256, 'ic13')
  await icns.appendImage(png128, 'ic07')
  await icns.appendImage(png64, 'ic12')
  await icns.appendImage(png32, 'ic05')
  await icns.appendImage(png16, 'ic04')  // <-- changed
  await icns.appendImage(png32, 'ic11')  // <-- changed
```

When I append `ic04` at the end, it doesn't seem to be displayed.
I don't know why, but this is very strange behavior. 🤔

**Comment by ezzatron** [comment]
Just to update, I tried again on the non-retina macOS machine, and couldn't reproduce any really bad corruption. The results are pretty much the same on a non-retina machine.

I think I must have got it mixed up in my head, because previously I tried using the `icp4`, `icp5`, and `icp6` types in my project. They produce nasty corruption like the images in this issue comment: https://github.com/avl7771/createicns/issues/1#issuecomment-373980734

**Comment by fiahfy** [comment]
OK.
But it is still strange that `ic04` or `ic05` does not appear in the Preview App when it is placed at the end.

**Comment by ezzatron** [comment]
Yeah, it's definitely strange. I guess either it's a bug in Preview, or there is some small issue with how they are encoded 🤷‍♂️

**Comment by fiahfy** [comment]
Fixed in https://github.com/fiahfy/icns/releases/tag/v0.0.6

**Comment by ezzatron** [comment]
Nice work!
